### ISSUE TITLE
Server IP address as the default

### ISSUE THREAD

**Issue by cdtinfo** [J-ISIS/J-ISIS#1]
Hi,
I have already ask this question on Kenai in september, but with no answer, so I try to re-post here.
I would like to set up an IP address of J-Isis server as the default address. Actually, when I open my client I have always "localhost" as address. 
Is there any possibility to change it? 
Thanks very much
Francesco

**Comment by jcd92410** [comment]
Dear Francesco,

I have added a parameter to specify the default server IP address as well as other parameters to simplify J-ISIS start. This will be available in next release.

Best wishes,
jcd

**Comment by cdtinfo** [comment]
Many thanks, Jean-Claude. I will wait for the next release. 
Best regards
Francesco

**Comment by jcd92410** [comment]
Dear Francesco,

In release 1.1 of 7 April 2017, you can define a default server IP address, the database name and home to open, as well as the default PFT name to use.

Best wishes,
JC
