### ISSUE TITLE
hebrew

### ISSUE THREAD

**Issue by aldoeri** [J-ISIS/J-ISIS#13]
hebrew is  not  working   i cant find terms  in hebrew 
![boceto 2](https://user-images.githubusercontent.com/25265688/42238776-9567acd0-7ec7-11e8-8d68-fced9cf2da82.png)
![boceto 3](https://user-images.githubusercontent.com/25265688/42238894-eec8c502-7ec7-11e8-8438-a0a9e5776a5d.png)

**Comment by jcd92410** [comment]
Hello,
Could you please check the dictionary if you see the Hebrew terms.
You may need to set the Hebrew font in the display if you use a special font
And finally, please send a small test database to check 
Best wishes 
Jean-Claude 

Envoyé de mon iPhone

**Comment by aldoeri** [comment]
[VERBOS.zip](https://github.com/J-ISIS/J-ISIS/files/2161164/VERBOS.zip)
there is my database

**Comment by aldoeri** [comment]
its working perfect thanks  a lot  i have change the Font
